import 'package:flutter/material.dart';

extension ArabicNameExtension on String {
  /// Apply only the hardcoded mapped names list.
  /// Returns original text if name not found.
  String toArabicName(BuildContext context) {
    if (this.isEmpty) return this;

    final langCode = Localizations.localeOf(context).languageCode;
    if (langCode != 'ar') return this;

    // Attempt map lookup case-insensitive.
    final key = this.trim().toLowerCase();
    return _famousPlayersMap[key] ?? this;
  }

  // Basic map for famous/common names to ensure accuracy
  static const Map<String, String> _famousPlayersMap = {
    'mohamed': 'محمد',
    'salah': 'صلاح',
    'lionel': 'ليونيل',
    'messi': 'ميسي',
    'cristiano': 'كريستيانو',
    'ronaldo': 'رونالدو',
    'kylian': 'كيليان',
    'mbappe': 'مبابي',
    'erling': 'إيرلينغ',
    'haaland': 'هالاند',
    'kevin': 'كيفين',
    'de bruyne': 'دي بروين',
    'neymar': 'نيمار',
    'vinicius': 'فينيسيوس',
    'junior': 'جونيور',
    'lewandowski': 'ليفاندوفسكي',
    'robert': 'روبرت',
    'karim': 'كريم',
    'benzema': 'بنزيما',
    'luka': 'لوكا',
    'modric': 'مودريتش',
    'virgil': 'فيرجيل',
    'van dijk': 'فان دايك',
    'alisson': 'أليسون',
    'ederson': 'إيدرسون',
    'rashford': 'راشفورد',
    'marcus': 'ماركوس',
    'bruno': 'برونو',
    'fernandes': 'فيرنانديز',
    'saka': 'ساكا',
    'bukayo': 'بوكايو',
    'son': 'سون',
    'heung-min': 'هيونغ مين',
    'kane': 'كين',
    'harry': 'هاري',
    'bellingham': 'بيلينجهام',
    'jude': 'جود',
    'pedri': 'بيدري',
    'gavi': 'جافي',
    'mbappé': 'مبابي',
    'ali': 'علي',
    'ahmed': 'أحمد',
    'omar': 'عمر',
    'hassan': 'حسن',
    'ibrahim': 'إبراهيم',
    'abdullah': 'عبدالله',
    'yousef': 'يوسف',
    'taremi': 'طارمي',
    'mahrez': 'محرز',
    'riyad': 'رياض',
    'hakimi': 'حكيمي',
    'achraf': 'أشرف',
    'ziyech': 'زياش',
    'hakim': 'حكيم',
    'bounou': 'بونو',
    'yassine': 'ياسين',
    'amrabat': 'أمرابط',
    'sofyan': 'سفيان',
    'mane': 'ماني',
    'sadio': 'ساديو',
    'mendy': 'ميندي',
    'koulibaly': 'كوليبالي',
    'silva': 'سيلفا',
    'bernardo': 'برناردو',
    'ruben': 'روبن',
    'dias': 'دياز',
    'cancelo': 'كانسيلو',
    'joao': 'جواو',
    'felix': 'فيليكس',
    'martinez': 'مارتينيز',
    'emiliano': 'إيميليانو',
    'lautaro': 'لاوتارو',
    'alvarez': 'ألفاريز',
    'julian': 'جوليان',
    'enzo': 'إنزو',
    'fernandez': 'فيرنانديز',
    'mac allister': 'ماك أليستر',
    'alexis': 'أليكسيس',
    'gabriel': 'غابرييل',
    'martin': 'مارتن',
    'odegaard': 'أوديغارد',
    'rice': 'رايس',
    'declan': 'ديكلان',
    'foden': 'فودين',
    'phil': 'فيل',
    'grealish': 'غريليش',
    'jack': 'جاك',
    'stones': 'ستونز',
    'john': 'جون',
    'walker': 'ووكر',
    'kyle': 'كايل',
    'rodri': 'رودري',
    'gundogan': 'غوندوغان',
    'ilkay': 'إيلكاي',
    'kroos': 'كروس',
    'toni': 'توني',
    'camavinga': 'كامافينجا',
    'eduardo': 'إدواردو',
    'tchouameni': 'تشواميني',
    'aurelien': 'أوريلين',
    'valverde': 'فالفيردي',
    'federico': 'فيديريكو',
    'courtois': 'كورتوا',
    'thibaut': 'تيبو',
    'militao': 'ميليتاو',
    'eder': 'إيدير',
    'rudiger': 'روديجر',
    'antonio': 'أنطونيو',
    'alaba': 'ألابا',
    'david': 'ديفيد',
    'carvajal': 'كارفخال',
    'dani': 'داني',
    'ter stegen': 'تير شتيغن',
    'marc-andre': 'مارك أندريه',
    'araujo': 'أراوخو',
    'ronald': 'رونالد',
    'kounde': 'كوندي',
    'jules': 'جول',
    'christensen': 'كريستنسن',
    'andreas': 'أندرياس',
    'balde': 'بالدي',
    'alejandro': 'أليخاندرو',
    'frenkie': 'فرينكي',
    'de jong': 'دي يونغ',
    'raphinha': 'رافينيا',
    'yamal': 'يامال',
    'lamine': 'لامين',
    'musiala': 'موسيالا',
    'jamal': 'جمال',
    'wirtz': 'فيرتز',
    'florian': 'فلوريان',
    'leao': 'لياو',
    'rafael': 'رافاييل',
    'theo': 'تيو',
    'maignan': 'ماينان',
    'mike': 'مايك',
    'osimhen': 'أوسيمين',
    'victor': 'فيكتور',
    'kvaratskhelia': 'كفاراتسخيليا',
    'khvicha': 'خفيشا',
    'dybala': 'ديبالا',
    'paulo': 'باولو',
    'lukaku': 'لوكاكو',
    'romelu': 'روميلو',
    'saliba': 'ساليبا',
    'william': 'ويليام',
    'jesus': 'جيسوس',
    'havertz': 'هافيرتز',
    'kai': 'كاي',
    'pulisic': 'بوليسيتش',
    'christian': 'كريستيان',
    'giroud': 'جيرو',
    'olivier': 'أوليفييه',
    'muller': 'مولر',
    'thomas': 'توماس',
    'sane': 'ساني',
    'leroy': 'ليروي',
    'coman': 'كومان',
    'kingsley': 'كينغسلي',
    'neuer': 'نوير',
    'manuel': 'مانويل',
    'upamecano': 'أوباميكانو',
    'dayot': 'دايوت',
    'kim': 'كيم',
    'min-jae': 'مين جاي',
    'davies': 'ديفيز',
    'alphonso': 'ألفونسو',
    'kimmich': 'كيميتش',
    'joshua': 'جوشوا',
    'goretzka': 'غوريتسكا',
    'leon': 'ليون',
    'gnabry': 'غنابري',
    'serge': 'سيرج',
    'arsenal': 'آرسنال',
    'chelsea': 'تشيلسي',
    'liverpool': 'ليفربول',
    'manchester city': 'مانشستر سيتي',
    'manchester united': 'مانشستر يونايتد',
    'tottenham': 'توتنهام',
    'hotspur': 'هوتسبر',
    'newcastle': 'نيوكاسل',
    'aston villa': 'أستون فيلا',
    'west ham': 'وست هام',
    'brighton': 'برايتون',
    'wolves': 'وولفز',
    'everton': 'إيفرتون',
    'crystal palace': 'كريستال بالاس',
    'brentford': 'برينتفورد',
    'nottingham forest': 'نوتينغهام فورست',
    'burnley': 'بيرنلي',
    'sheffield united': 'شيفيلد يونايتد',
    'luton town': 'لوتون تاون',
    'bournemouth': 'بورنموث',
    'fulham': 'فولهام',
  };

  // No transliteration fallback is used; map-only behavior is active.
}
